config/routes.rb
ImageGallery::Application.routes.draw do
  resources :galleries do
     resources :images
  end

  resources :users

 root :to => "galleries#index"

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  # Gallery model
  # created by tapan
  # created on 04/05/2012
  attr_accessible :name , :image 
   has_many :images ,:dependent => :destroy
   accepts_nested_attributes_for :images, :allow_destroy => true
end

app/models/image.rb
require 'paperclip' 
class Image < ActiveRecord::Base
  # Image model
  # created by tapan
  # created on 04/05/2012
   attr_accessible :name, :isActive

   belongs_to :user
   belongs_to :gallery
   has_attached_file :upload,
                    :url => "/images/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/images/:id/:style/:basename.:extension",
                    :styles => {
                      :thumb => "75x75>",
                      :small => "200x200>"
                    }
  #add in any validations you may want
end

app/models/user.rb
class User < ActiveRecord::Base
  # User model
  # created by tapan
  # created on 04/05/2012
  has_many :images
  attr_accessible :name, :email, :address ,:dob,:password_confirmation,:password
  attr_accessor :password
  validates :name,:presence => true,:length => { :maximum => 50 }
   email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,:presence => true ,:format=> { :with => email_regex },:uniqueness => {:case_sensitive => false }
  validates :password, :presence=> true,:confirmation => true,:length=> { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
 private
def encrypt_password
self.salt = make_salt if new_record?
self.encrypted_password = encrypt(password)
end
def encrypt(string)
secure_hash("#{salt}--#{string}")
end
def make_salt
secure_hash("#{Time.now.utc}--#{password}")
end
def secure_hash(string)
Digest::SHA2.hexdigest(string)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  #created by tapan
  #created_on:07/05/2012
  #purpose: new gallry form

  def new
    @gallery = Gallery.new
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: show a gallery

  def show
    @gallery = Gallery.find(params[:id])
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: show list of galleries

  def index
    @galleries = Gallery.all
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: edit a gallery

  def edit
    @gallery = Gallery.find(params[:id])
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: create a new gallery

  def create
     @gallery = Gallery.new(params[:gallery])
    if @gallery.save
      redirect_to @gallery
      return
    else
       redirect_to root_path
    end
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: update a gallery

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update_attributes(params[:gallery])
      redirect_to @gallery
      return
    else
      redirect_to request.referer
    end
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: delete a gallery

  def delete
    
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
     @title = "Sigm in"
  end

  def create
   user = User.authenticate(params[:session][:email],
   params[:session][:password])
   if user.nil?
    flash.now[:error] = "Invalid email/password combination."
    render 'new'
   else
    sign_in user
    redirect_to user
    session[:expires_at] = 2.seconds.from_now

   end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_filter :check_login, :except =>[:new,:create]
  #created by tapan
  #created_on:04/05/2012
  #purpose: new user form

  def new
    @user = User.new
     respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: to show all users

  def index
   @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: to show a user

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: to create a new user

  def create
    @user = User.new(params[:user])
    respond_to do |format|
    if @user.save
      format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end
  end
  #created by tapan
  #created_on:04/05/2012
  #purpose: to edit an existing user

  def edit
     @user = User.find(params[:id])
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: to update an existing user

  def update
     @user = User.find(params[:id])
      respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  #created by tapan
  #created_on:04/05/2012
  #purpose: to delete an existing user

  def destroy
    @user = User.find(params[:id])
    @user.destroy
     respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  def check_login
    redirect_to root_url unless current_user
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper

  def add_object_link(name, form, object, partial, where)
      html = render(:partial => partial, :locals => { :form => form}, :object => object)
      link_to_function name, %{
        var new_object_id = new Date().getTime() ;
        var html = jQuery(#{js html}.replace(/index_to_replace_with_js/g, new_object_id)).hide();
        html.appendTo(jQuery("#{where}")).slideDown('slow');
      }
    end
  def js(data)
      if data.respond_to? :to_json
        data.to_json
      else
        data.inspect.to_json
      end
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user ||= user_from_remember_token
  end
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    current_user = nil
  end

private
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<% form_for(@gallery, :html => { :multipart => true }) do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <b> Picture </b><br/>
    <%= f.file_field :image %>
  </div>
  
  <p><%= f.submit %></p>
<% end %>

app/views/galleries/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h1>Edit Image Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h1>Listing galleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Photo Title</th>
    <th>Photos</th>
  </tr>

<% @galleries.each do |album| %>
  <tr>
    <td><%= album.name %></td>
  <% album.images.each do |photo| %>
    <td><%= photo.title %></td>
    <td><%= image_tag photo.upload.url(:thumb) %></td>
  <% end %>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_gallery_path(album) %></td>
    <td><%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New album', new_gallery_path %>

app/views/galleries/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%#
# created by tapan. Last modified on 04/05/2012
# This is view page for creating new user
%>

<h1>Create Gallery Here</h1>
<%= form_for(@gallery) do |f| %>
<div>
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>

<div class="actions">
<%= f.submit "Create" %>
</div>
<% end %>

app/views/galleries/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<p>
  <b>Name:</b>
  <%= @gallery.name %><br />
  

  <% @gallery.images.each do |photo| %>

    <h3><%=photo.name %></h3>
    <%= image_tag photo.upload.url(:small) %>
  <% end %>
</p>
<%= link_to "upload",new_gallery_image_path(@gallery) %>
<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageGallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password, "current password" %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation , "confirm your current password"%><br />
    <%= f.password_field :password_confirmation %>
  </div>

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<%#
# created by tapan. Last modified on 04/05/2012
# This is view page for listing all users
%>

<h1>Listing all users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%#
# created by tapan. Last modified on 04/05/2012
# This is view page for creating new user
%>

<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
<div>
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div>
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div>
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div>
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>

<div>
<%= f.label :dob, "Date of Birth" %><br />
<%= f.text_field :dob %>
</div>
<div class="actions">
<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<%#
# created by tapan. Last modified on 04/05/2012
# This is view page for showing a specified user
%>

<div>
 <%= @user.name %>
</div>
<div>
  <strong>Name:</strong> <%= @user.name %>&nbsp;<%= link_to 'Go Back ', :back %><br />
</div>